services:
  asir_bind9:
    container_name: asir_bind9
    image: internetsystemsconsortium/bind9:9.16
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
      mired:
        ipv4_address: 172.28.5.254
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind
  asir_cliente:
    container_name: asir_cliente
    image: alpine
    networks:
      - mired
    stdin_open: true  
    tty: true         
    dns:
      - 172.28.5.254  
networks:
  mired: 
    external: true





